### ISSUE TITLE
Does pg-info (later combined with pg-model) not handle the Composite-Types of Postgres?

### ISSUE THREAD

**Issue by phocs** [wmfs/pg-info#103]
In my database I have some Composite-Types, like:

` CREATE TYPE TYPE_EXECUTOR AS (
    team_id        VARCHAR(21),
    employee_id    VARCHAR(20)
);`

With pg-info I get: `dataType: 'USER-DEFINED'`

and as a result of `pg-model.find()` a string: `executor: '("TIDXXXXXX,"EIDXXXXXX")'`

So, does pg-info (later combined with pg-model) not handle the Composite-Types of Postgres?

Or, how can I manage them?

**Comment by timneedham** [comment]
Hi @phocs ... thanks for raising this issue.

I've been able to replicate the scenario you describe... and have dug into it a bit.

I'm afraid support for composite-types in `pg-info` and `pg-model` isn't explicit yet. They are't queried for and bundled in the collated information.

That said...

`pg-info` uses this query to derive column data:

```
select 
  table_schema, 
  table_name, 
  column_name, 
  column_default, 
  is_nullable, 
  data_type, 
  character_maximum_length, 
  numeric_scale, 
  pg_catalog.col_description(format('%s.%s',isc.table_schema,isc.table_name)::regclass::oid,isc.ordinal_position) as column_comment, 
  udt_name as array_element_type
 from information_schema.columns isc 
 where table_schema = 'public'
 and table_name='composite_test'
 order by ordinal_position;
```

**Which gives:**

![image](https://user-images.githubusercontent.com/1216632/56574345-e6157880-65ba-11e9-8561-f598eebce710.png)

...like you say, `data_type` is returned as `USER-DEFINED`.

* As in the pic above, the name of the type is available via the `array-element-type` column? (e.g. `array_element_type`) Is that something that might be useful, if we looked to exposing it?
